
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lecture des fichiers et installation des librairies nécesssaires
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(scales)

cleanWater <- read.csv("../Dataset/share-without-improved-water.csv", header = TRUE)

```

```{r}
cleanWater <- cleanWater %>% filter(Year < 2011) %>% filter(Code != "") %>% filter(!Entity %in% c("Gibraltar", "Sint Maarten (Dutch part)", "Cayman Islands"))
cleanWater <- select(cleanWater, -`Code`)
colnames(cleanWater) <- c("Country", "Year", "Proportion of population unable to access clean water (%)")
cleanWater$`Proportion of population unable to access clean water (%)` <- round((cleanWater$`Proportion of population unable to access clean water (%)`), 2)
```

```{r}
cleanWater_mean <- cleanWater %>%
  group_by(Country) %>%
  summarise(`Proportion of population unable to access clean water (%)` = mean(`Proportion of population unable to access clean water (%)`))

cleanWater_max <- cleanWater_mean %>% top_n(wt = `Proportion of population unable to access clean water (%)`, n = 10) 

cleanWater_min <- cleanWater_mean %>% slice_min(`Proportion of population unable to access clean water (%)`, n = 10) %>% slice_head(n = 10)

cleanWater_minmax <- rbind(cleanWater_min, cleanWater_max)

cleanWater_minmax$Country <- factor(cleanWater_minmax$Country, levels = cleanWater_minmax$Country[order(cleanWater_minmax$`Proportion of population unable to access clean water (%)`)])
```

```{r}
ggplot(cleanWater_minmax, aes(x= Country, y=`Proportion of population unable to access clean water (%)`)) + geom_bar(stat = "identity") + labs(title="Proportion de la population n'ayant pas accès à l'eau courante", x="Pays", y="Proportion (en %)") + scale_fill_discrete(name = "Country") +  # Customizing legend title 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotating x-axis labels for better readability
```

```{r}
ProportionCleanWater <- merge(cleanWater_minmax, annualdeath[c("Country", "Infectious diseases prop (%)")], by = "Country")
ProportionCleanWater <- ProportionCleanWater %>% group_by(Country) %>% summarize(`Infectious diseases %` = mean(`Infectious diseases prop (%)`), `Proportion of population unable to access clean water (%)` = mean(`Proportion of population unable to access clean water (%)`))

ggplot(ProportionCleanWater, aes(x= Country, y=`Infectious diseases %`)) + geom_bar(stat = "identity") + labs(title="Proportion de personnes mortes de maladies infectieuses", x="Pays", y="Quantité (en %)") + scale_y_continuous(labels = comma_format()) + scale_fill_discrete(name = "Country") +  # Customizing legend title 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotating x-axis labels for better readability
```